### PR TITLE
Added API version

### PR DESCRIPTION
**Pull request by TonyDroidd**

### CODE REVIEW

**Comment by xxFlare** [comment]
:+1:

**Comment by L3ice** [comment]
Yeah API is 1.0.0 ...
xD

**Comment by TruDan** [comment]
We're actually using 1.12.0, not 1.0.0 :P ->getUniqueId() doesnt exist in 1.0.0

**Comment by TonyDroidd** [comment]
I thought it was for PocketMine 1.4 xD

**Comment by TruDan** [comment]
By the time it's stable enough for production use, PM 1.5 will be the release build anyway :P

**Pull request closed without merging**
